using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Radar.Core.Analysis;
using Radar.Core.Model;

namespace Radar.Core.Reporting;

/// <summary>
/// Relatório de investigação exportável: dossiê completo com timeline, indicadores e
/// evidências, para levar a um técnico, fórum ou fabricante de antivírus. HTML e JSON.
/// </summary>
public sealed record InvestigationReport
{
    public required ProcessExecution Execution { get; init; }
    public IReadOnlyList<TimelineEvent> Timeline { get; init; } = [];
    public IReadOnlyList<NetworkConnection> Connections { get; init; } = [];
    public IReadOnlyList<DnsQuery> DnsQueries { get; init; } = [];
    public IReadOnlyList<FileActivity> FileActivities { get; init; } = [];
    public IReadOnlyList<PersistenceEntry> RelatedPersistence { get; init; } = [];
    public IReadOnlyList<ProcessExecution> RelatedExecutions { get; init; } = [];
    public DateTimeOffset GeneratedUtc { get; init; }
    public string GeneratorVersion { get; init; } = "Radar 0.1.0";

    /// <summary>Indicadores prontos para copiar: hash, caminho, domínios, IPs, formatados.</summary>
    public string FormatIndicators()
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Indicators - {Execution.Binary.FileName}");
        sb.AppendLine($"SHA-256: {Execution.Binary.Sha256 ?? "(not computed)"}");
        sb.AppendLine($"Path: {Execution.Binary.Path}");
        if (Execution.CommandLine is { } cl) sb.AppendLine($"Command line: {cl}");
        var domains = DnsQueries.Select(d => d.Domain).Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        if (domains.Count > 0) sb.AppendLine($"Domains: {string.Join(", ", domains)}");
        var ips = Connections.Select(c => $"{c.RemoteAddress}:{c.RemotePort}").Distinct().ToList();
        if (ips.Count > 0) sb.AppendLine($"Endpoints: {string.Join(", ", ips)}");
        return sb.ToString();
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Converters = { new JsonStringEnumConverter() },
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public string ToJson() => JsonSerializer.Serialize(this, JsonOptions);

    public string ToHtml()
    {
        var e = Execution;
        var score = e.Score ?? SuspicionScore.Empty;
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"utf-8\">");
        sb.AppendLine($"<title>Radar - Investigation Report: {H(e.Binary.FileName)}</title>");
        sb.AppendLine("""
            <style>
            body{font-family:'Segoe UI',sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#1a1a1a;background:#fafafa}
            h1{border-bottom:3px solid #c50f1f;padding-bottom:.5rem} h2{margin-top:2rem;color:#333}
            table{border-collapse:collapse;width:100%;background:#fff} th,td{border:1px solid #ddd;padding:.45rem .6rem;text-align:left;font-size:.9rem}
            th{background:#f0f0f0} .band-Critical{color:#c50f1f;font-weight:700} .band-Suspicious{color:#ca5010;font-weight:700}
            .band-Attention{color:#986f0b} .band-Informational{color:#107c10}
            .signal{background:#fff;border-left:4px solid #c50f1f;margin:.5rem 0;padding:.5rem .8rem}
            .signal.reducer{border-left-color:#107c10} .weight{font-weight:700} .evidence{color:#666;font-size:.85rem}
            code{background:#eee;padding:.1rem .3rem;border-radius:3px;font-size:.85rem;word-break:break-all}
            footer{margin-top:3rem;color:#888;font-size:.8rem;border-top:1px solid #ddd;padding-top:1rem}
            </style></head><body>
            """);
        sb.AppendLine($"<h1>Investigation Report - {H(e.Binary.FileName)}</h1>");
        sb.AppendLine($"<p>Generated by {H(GeneratorVersion)} on {GeneratedUtc.ToLocalTime():dd/MM/yyyy HH:mm:ss}.</p>");

        sb.AppendLine("<h2>Identity</h2><table>");
        Row(sb, "Path", $"<code>{H(e.Binary.Path)}</code>");
        Row(sb, "SHA-256", $"<code>{H(e.Binary.Sha256 ?? "(not computed)")}</code>");
        Row(sb, "Size", ScoreEngine.FormatBytes(e.Binary.SizeBytes));
        Row(sb, "Command line", $"<code>{H(e.CommandLine ?? "-")}</code>");
        Row(sb, "Vendor (metadata)", H(e.Binary.Version.CompanyName ?? "-"));
        Row(sb, "Signature", H(DescribeSignature(e.Binary.Signature)));
        if (e.Binary.Motw is { } motw)
            Row(sb, "Mark of the Web", $"Zone {motw.ZoneId}{(motw.HostUrl is { } u ? $", origin {H(u)}" : string.Empty)}");
        Row(sb, "Created", e.CreatedUtc.ToLocalTime().ToString("dd/MM/yyyy HH:mm:ss.fff"));
        Row(sb, "Exited", e.ExitedUtc?.ToLocalTime().ToString("dd/MM/yyyy HH:mm:ss.fff") ?? "still running");
        Row(sb, "Duration", ScoreEngine.FormatDuration(e.Duration));
        Row(sb, "User", $"{H(e.Security.UserName ?? "?")} ({e.Security.AccountKind}, integrity {e.Security.IntegrityLevel})");
        if (e.Origin is { } origin) Row(sb, "Launch origin", H(origin.Description));
        sb.AppendLine("</table>");

        sb.AppendLine($"<h2>Suspicion score: <span class=\"band-{score.Band}\">{score.Total} ({BandPt(score.Band)})</span></h2>");
        foreach (var s in score.Signals)
        {
            sb.AppendLine($"<div class=\"signal\"><span class=\"weight\">+{s.Weight}</span> - <strong>{H(s.Title)}</strong><br>{H(s.Explanation)}");
            if (s.Evidence.Count > 0)
                sb.AppendLine($"<div class=\"evidence\">Evidence: {string.Join("; ", s.Evidence.Select(H))}</div>");
            sb.AppendLine("</div>");
        }
        foreach (var r in score.Reducers)
            sb.AppendLine($"<div class=\"signal reducer\"><span class=\"weight\">{r.Weight}</span> - <strong>{H(r.Title)}</strong><br>{H(r.Explanation)}</div>");

        if (Timeline.Count > 0)
        {
            sb.AppendLine("<h2>Execution timeline</h2><table><tr><th>Time</th><th>Event</th><th>Detail</th></tr>");
            foreach (var t in Timeline.OrderBy(t => t.TimestampUtc))
                sb.AppendLine($"<tr><td>{t.TimestampUtc.ToLocalTime():HH:mm:ss.fff}</td><td>{H(t.Title)}</td><td>{H(t.Detail ?? string.Empty)}</td></tr>");
            sb.AppendLine("</table>");
        }

        if (Connections.Count > 0 || DnsQueries.Count > 0)
        {
            sb.AppendLine("<h2>Network</h2><table><tr><th>Destination</th><th>Origin domain</th><th>Sent</th><th>Received</th></tr>");
            foreach (var c in Connections)
                sb.AppendLine($"<tr><td>{H(c.RemoteAddress)}:{c.RemotePort}/{c.Protocol}</td><td>{H(c.ResolvedFromDomain ?? "direct IP (no DNS)")}</td>" +
                              $"<td>{ScoreEngine.FormatBytes(c.BytesSent)}</td><td>{ScoreEngine.FormatBytes(c.BytesReceived)}</td></tr>");
            sb.AppendLine("</table>");
            if (DnsQueries.Count > 0)
                sb.AppendLine($"<p>Domains queried: {string.Join(", ", DnsQueries.Select(d => $"<code>{H(d.Domain)}</code>").Distinct())}</p>");
        }

        if (FileActivities.Count > 0)
        {
            sb.AppendLine("<h2>Files</h2><table><tr><th>Time</th><th>Type</th><th>Path</th><th>Hash</th></tr>");
            foreach (var f in FileActivities)
                sb.AppendLine($"<tr><td>{f.TimestampUtc.ToLocalTime():HH:mm:ss}</td><td>{FileKindPt(f.Kind)}{(f.SensitiveCategory is { } c ? $" - {H(c)}" : string.Empty)}</td>" +
                              $"<td><code>{H(f.Path)}</code></td><td><code>{H(f.Sha256 ?? "-")}</code></td></tr>");
            sb.AppendLine("</table>");
        }

        if (RelatedPersistence.Count > 0)
        {
            sb.AppendLine("<h2>Related persistence</h2><table><tr><th>Type</th><th>Location</th><th>Name</th><th>Target</th><th>Seen on</th></tr>");
            foreach (var p in RelatedPersistence)
                sb.AppendLine($"<tr><td>{p.Kind}</td><td><code>{H(p.Location)}</code></td><td>{H(p.Name)}</td><td><code>{H(p.Target)}</code></td><td>{p.FirstSeenUtc.ToLocalTime():dd/MM/yyyy HH:mm}</td></tr>");
            sb.AppendLine("</table>");
        }

        sb.AppendLine("<h2>Indicators (to copy)</h2>");
        sb.AppendLine($"<pre>{H(FormatIndicators())}</pre>");

        sb.AppendLine("<footer>Radar is not an antivirus: a high score is not a malware verdict; a low score is not a certificate of innocence. " +
                      "This report records observed evidence for human judgment.</footer>");
        sb.AppendLine("</body></html>");
        return sb.ToString();

        static void Row(StringBuilder sb, string label, string valueHtml) =>
            sb.AppendLine($"<tr><th style=\"width:220px\">{H(label)}</th><td>{valueHtml}</td></tr>");
    }

    public static string DescribeSignature(SignatureInfo sig) => sig.Status switch
    {
        SignatureStatus.SignedTrusted =>
            $"Signed and trusted - {sig.Subject ?? "?"}{(sig.IsCatalogSigned ? " (catalog signature)" : string.Empty)}",
        SignatureStatus.SignedWithCaveats => $"Signed with caveats - {sig.Details ?? sig.Subject ?? "?"}",
        SignatureStatus.SignedInvalid => "INVALID SIGNATURE - the binary was altered after it was signed",
        SignatureStatus.SignedRevoked => "REVOKED CERTIFICATE - often a stolen certificate",
        SignatureStatus.SelfSigned => $"Self-signed ({sig.Subject ?? "?"})",
        SignatureStatus.Unsigned => "Unsigned",
        _ => "Verification pending",
    };

    public static string BandPt(ScoreBand band) => band switch
    {
        ScoreBand.Critical => "Critical",
        ScoreBand.Suspicious => "Suspicious",
        ScoreBand.Attention => "Attention",
        _ => "Informational",
    };

    private static string FileKindPt(FileEventKind kind) => kind switch
    {
        FileEventKind.SensitiveRead => "Sensitive read",
        FileEventKind.ExecutableDrop => "Executable drop",
        FileEventKind.SelfDelete => "Self-deletion",
        FileEventKind.ArchiveStaging => "Suspicious archiving (staging)",
        _ => "Write",
    };

    private static string H(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
}
